AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  woof-app

  Sample SAM Template for woof-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 8

Resources:
  WoofApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      # Cors: "'*'"
      # Auth:
      #   DefaultAuthorizer: MyCognitoAuthorizer
      # Authorizers:
      #   MyCognitoAuthorizer:
      #     UserPoolArn: !GetAtt MyCognitoUserPool.Arn
  PublisherFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code/
      Handler: publishMessage.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          topicArn: !Ref PublisherSns
          tableName: !Ref MessagesTable
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt PublisherSns.TopicName
      Events:
        Publish:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref WoofApi
            Path: /publish_message
            Method: post

  AddFriendFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code/
      Handler: addFriend.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          tableName: !Ref UserFriendsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserFriendsTable
      Events:
        Publish:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref WoofApi
            Path: /add_friend
            Method: post

  GetFriendsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code/
      Handler: getFriends.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          tableName: !Ref UserFriendsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserFriendsTable
      Events:
        Publish:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref WoofApi
            Path: /get_friends
            Method: get

  GetMessagesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code/
      Handler: getMessages.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          tableName: !Ref MessagesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
      Events:
        Publish:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref WoofApi
            Path: /get_messages
            Method: get

  PublisherSns:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: WOOF ###
      TopicName: PublisherSns

  UserFriendsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: "userFriends"
      AttributeDefinitions:
        - AttributeName: "user_email"
          AttributeType: "S"
        - AttributeName: "user_friend"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "user_email"
          KeyType: "HASH"
        - AttributeName: "user_friend"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  MessagesTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: "messages"
      AttributeDefinitions:
        - AttributeName: "user_email"
          AttributeType: "S"
        - AttributeName: "timestamp"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "user_email"
          KeyType: "HASH"
        - AttributeName: "timestamp"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  # TestSnsSubscription:
  #   Type: AWS::SNS::Subscription
  #   Properties:
  #     Endpoint: solon.seficha@pfizer.com
  #     Protocol: email
  #     TopicArn: !Ref PublisherSns
# Outputs:
# ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
# Find out more about other implicit resources you can reference within SAM
# https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
# HelloWorldApi:
#   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
# HelloWorldFunction:
#   Description: "Hello World Lambda Function ARN"
#   Value: !GetAtt HelloWorldFunction.Arn
# HelloWorldFunctionIamRole:
#   Description: "Implicit IAM Role created for Hello World function"
#   Value: !GetAtt HelloWorldFunctionRole.Arn
